"""market quote unit/basis, knowledge access_scope constraint

Revision ID: 920d032f1591
Revises: 6ac2490bd8b9
Create Date: 2026-08-11 22:43:16.440797
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '920d032f1591'
down_revision: Union[str, None] = '6ac2490bd8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_knowledge_documents_access_scope', 'knowledge_documents', "access_scope IN ('ORG', 'OWNER')")
    op.add_column('market_quotes', sa.Column('unit', sa.String(length=24), nullable=True))
    op.add_column('market_quotes', sa.Column('basis', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_quotes', 'basis')
    op.drop_column('market_quotes', 'unit')
    op.drop_constraint('ck_knowledge_documents_access_scope', 'knowledge_documents', type_='check')
    # ### end Alembic commands ###
