"""alert open unique, inventory lot unique

Revision ID: e3dc4562f38d
Revises: 920d032f1591
Create Date: 2026-08-12 00:02:29.496814
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3dc4562f38d'
down_revision: Union[str, None] = '920d032f1591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_inventory_alerts_open_product_type', 'inventory_alerts', ['organization_id', 'product_id', 'alert_type'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_unique_constraint('uq_inventory_lots_org_product_wh_lot', 'inventory_lots', ['organization_id', 'product_id', 'warehouse_id', 'lot_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inventory_lots_org_product_wh_lot', 'inventory_lots', type_='unique')
    op.drop_index('uq_inventory_alerts_open_product_type', table_name='inventory_alerts', postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###
